'use client';

import { useState, useEffect, useRef } from 'react';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui';
import { Workout, InBodyEntry } from '@/types';

interface ProteinEstimateProps {
  workouts: Workout[];
  inBodyEntries: InBodyEntry[];
}

interface ProteinData {
  estimatedDailyIntake: number;
  recommendedDailyIntake: number;
  explanation: string;
}

export function ProteinEstimate({ workouts, inBodyEntries }: ProteinEstimateProps) {
  const [data, setData] = useState<ProteinData | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const hasFetched = useRef(false);

  useEffect(() => {
    if (hasFetched.current) return;
    if (workouts.length === 0 && inBodyEntries.length === 0) return;

    hasFetched.current = true;

    const fetchEstimate = async () => {
      setLoading(true);
      setError(null);

      try {
        // Read from pre-cached protein estimate (generated by cache warmer)
        const res = await fetch('/api/protein');

        if (!res.ok) {
          // Fallback: compute from body weight if cache is empty
          const latestWeight = inBodyEntries.length > 0
            ? [...inBodyEntries].sort((a, b) => b.date.getTime() - a.date.getTime())[0].weight
            : null;
          if (latestWeight) {
            setData({
              estimatedDailyIntake: Math.round(latestWeight * 0.7),
              recommendedDailyIntake: Math.round(latestWeight * 0.9),
              explanation: 'Estimated based on body weight. AI estimate will be available after next cache refresh.',
            });
          } else {
            throw new Error('Protein estimate not cached yet');
          }
          return;
        }

        const result = await res.json();

        const estimated = result.estimatedDailyIntake ?? result.estimated_daily_intake;
        const recommended = result.recommendedDailyIntake ?? result.recommended_daily_intake;
        const explanation = result.explanation ?? result.analysis ?? '';

        if (estimated != null && recommended != null) {
          setData({
            estimatedDailyIntake: Math.round(estimated),
            recommendedDailyIntake: Math.round(recommended),
            explanation,
          });
        } else {
          throw new Error('Unexpected response format');
        }
      } catch (err) {
        setError(err instanceof Error ? err.message : 'Failed to estimate protein');
      } finally {
        setLoading(false);
      }
    };

    fetchEstimate();
  }, [workouts, inBodyEntries]);

  const latestInBody = inBodyEntries.length > 0
    ? [...inBodyEntries].sort((a, b) => b.date.getTime() - a.date.getTime())[0]
    : null;

  if (workouts.length === 0 && inBodyEntries.length === 0) {
    return (
      <Card>
        <CardHeader>
          <CardTitle>Protein Estimate</CardTitle>
        </CardHeader>
        <CardContent>
          <p className="font-mono text-xs text-n-text-disabled uppercase tracking-[0.04em] text-center py-4">
            [LOG WORKOUTS AND BODY COMPOSITION FOR ESTIMATES]
          </p>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle>Protein Estimate</CardTitle>
        <p className="text-xs text-n-text-disabled mt-1">
          AI-estimated daily protein based on your training and body composition
        </p>
      </CardHeader>
      <CardContent>
        {loading && (
          <div className="text-center py-8">
            <p className="font-mono text-[11px] uppercase tracking-[0.08em] text-n-text-disabled">
              [ANALYZING...]
            </p>
          </div>
        )}

        {error && (
          <div className="text-center py-8">
            <p className="font-mono text-[11px] uppercase tracking-[0.08em] text-n-text-disabled">
              [ERROR: {error.toUpperCase()}]
            </p>
          </div>
        )}

        {data && !loading && (
          <div className="space-y-4">
            {/* Big numbers */}
            <div className="grid grid-cols-2 gap-3">
              <div className="p-4 bg-n-surface-raised rounded-nothing-sm text-center">
                <p className="font-mono text-[10px] uppercase tracking-[0.08em] text-n-text-disabled mb-2">
                  Estimated Intake
                </p>
                <p className="font-mono text-3xl tracking-tight text-n-text-display">
                  {data.estimatedDailyIntake}
                  <span className="text-sm text-n-text-secondary ml-1">g</span>
                </p>
                <p className="font-mono text-[10px] uppercase tracking-[0.08em] text-n-text-disabled mt-1">
                  per day
                </p>
              </div>

              <div className="p-4 border border-n-border-visible rounded-nothing-sm text-center">
                <p className="font-mono text-[10px] uppercase tracking-[0.08em] text-n-text-disabled mb-2">
                  Recommended
                </p>
                <p className="font-mono text-3xl tracking-tight text-n-accent">
                  {data.recommendedDailyIntake}
                  <span className="text-sm text-n-text-secondary ml-1">g</span>
                </p>
                <p className="font-mono text-[10px] uppercase tracking-[0.08em] text-n-text-disabled mt-1">
                  per day
                </p>
              </div>
            </div>

            {/* Gap indicator */}
            {data.estimatedDailyIntake < data.recommendedDailyIntake && (
              <div className="px-4 py-3 border border-n-border rounded-nothing-sm">
                <div className="flex items-center justify-between">
                  <span className="font-mono text-[10px] uppercase tracking-[0.08em] text-n-text-disabled">
                    Deficit
                  </span>
                  <span className="font-mono text-[11px] uppercase tracking-[0.04em] text-n-accent">
                    {data.recommendedDailyIntake - data.estimatedDailyIntake}g below target
                  </span>
                </div>
              </div>
            )}

            {data.estimatedDailyIntake >= data.recommendedDailyIntake && (
              <div className="px-4 py-3 border border-n-border rounded-nothing-sm">
                <div className="flex items-center justify-between">
                  <span className="font-mono text-[10px] uppercase tracking-[0.08em] text-n-text-disabled">
                    Status
                  </span>
                  <span className="font-mono text-[11px] uppercase tracking-[0.04em] text-n-success">
                    Meeting target
                  </span>
                </div>
              </div>
            )}

            {/* Body weight context */}
            {latestInBody && (
              <div className="grid grid-cols-3 gap-2">
                <div className="p-3 bg-n-surface-raised rounded-nothing-xs text-center">
                  <p className="font-mono text-[9px] uppercase tracking-[0.08em] text-n-text-disabled mb-1">
                    Body Weight
                  </p>
                  <p className="font-mono text-sm text-n-text-secondary">
                    {latestInBody.weight} lbs
                  </p>
                </div>
                <div className="p-3 bg-n-surface-raised rounded-nothing-xs text-center">
                  <p className="font-mono text-[9px] uppercase tracking-[0.08em] text-n-text-disabled mb-1">
                    Muscle Mass
                  </p>
                  <p className="font-mono text-sm text-n-text-secondary">
                    {latestInBody.muscleMass} lbs
                  </p>
                </div>
                <div className="p-3 bg-n-surface-raised rounded-nothing-xs text-center">
                  <p className="font-mono text-[9px] uppercase tracking-[0.08em] text-n-text-disabled mb-1">
                    g/lb Body Wt
                  </p>
                  <p className="font-mono text-sm text-n-text-secondary">
                    {(data.recommendedDailyIntake / latestInBody.weight).toFixed(2)}
                  </p>
                </div>
              </div>
            )}

            {/* AI Explanation */}
            {data.explanation && (
              <div className="px-4 py-3 border-l-2 border-l-n-border-visible">
                <p className="text-sm text-n-text-secondary leading-relaxed">
                  {data.explanation}
                </p>
              </div>
            )}
          </div>
        )}
      </CardContent>
    </Card>
  );
}

